services:
  - type: web
    name: selfcast-onboard
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_HOST
        value: mail.selfcaststudios.com
      - key: EMAIL_USER
        value: welcome@selfcaststudios.com
      - key: EMAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        value: https://onboard.selfcaststudios.com
    autoDeploy: true
